module.exports = {
  reactStrictMode: true,
  env: {
    REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
    REACT_APP_AUTH_DOMAIN: process.env.REACT_APP_AUTH_DOMAIN,
    REACT_APP_PROJECT_ID: process.env.REACT_APP_PROJECT_ID,
    REACT_APP_STORAGE_BUCKET: process.env.REACT_APP_STORAGE_BUCKET,
    REACT_APP_MESSAGING_SENDER_ID: process.env.REACT_APP_MESSAGING_SENDER_ID,
    REACT_APP_APP_ID: process.env.REACT_APP_APP_ID,
    REACT_APP_MEASUREMENT_ID: process.env.REACT_APP_MEASUREMENT_ID,
    REACT_APP_ADMIN_ID: process.env.REACT_APP_ADMIN_ID,
    REACT_APP_PAYMONGO_PUBLIC_KEY: process.env.REACT_APP_PAYMONGO_PUBLIC_KEY,
    REACT_APP_PAYMONGO_SECRET_KEY: process.env.REACT_APP_PAYMONGO_SECRET_KEY,
    REACT_APP_SENDGRID_API_KEY: process.env.REACT_APP_SENDGRID_API_KEY,
    REACT_APP_THESMSWORKS_API_KEY: process.env.REACT_APP_THESMSWORKS_API_KEY,
    REACT_APP_ADMIN_EMAIL: process.env.REACT_APP_ADMIN_EMAIL,
    REACT_APP_EMAILJS_SERVICE_ID: process.env.REACT_APP_EMAILJS_SERVICE_ID,
  },
  images: {
    domains: ["nxtgeneclinic.com.ph", "firebasestorage.googleapis.com"],
  },
};
