import format from "date-fns/format";
import Head from "next/head";
import Image from "next/image";
import AmendClinicHoursModal from "../components/AmendClinicHoursModal";
import EditClinicHoursModal from "../components/EditClinicHoursModal";
import Calendar from "../components/Calendar";
import Header from "../components/Header";
import SignInModal from "../components/SignInModal";
import SignUpModal from "../components/SignUpModal";
import UserDetailsModal from "../components/UserDetailsModal";

import { useSelectedDateContext } from "../contextProvider/SelectedDateContext";
import { useSignInContext } from "../contextProvider/SignInContext";
import HolidaysModal from "../components/HolidaysModal";
import OurDoctors from "../components/OurDoctors";
import SpecialistDetailsModal from "../components/SpecialistDetailsModal";
import AppointmentBookingModal from "../components/AppointmentBookingModal";
import { ContactUs } from "../components/EmailForm";
import ContactUsModal from "../components/ContactUsModal";
import PaymongoHome from "./paymongoindex";
import Cart from "./cart";
import Payment from "./payment";
import UserRolesModal from "../components/UserRolesModal";
import CalendarOverview from "../components/CalendarOverview";
import { useEffect } from "react";

import { motion, AnimatePresence } from "framer-motion";

export default function Home() {
  const { selectedDate } = useSelectedDateContext();
  const {
    signInModal,
    setSignInModal,
    signUpModal,
    setSignUpModal,
    forgotPasswordModal,
    setForgotPasswordModal,
    currentUserID,
    setCurrentUserID,
    userDetailsModal,
    setUserDetailsModal,
    specialistDetailsModal,
    setSpecialistDetailsModal,
    amendClinicHoursModal,
    setAmendClinicHoursModal,
    editClinicHoursModal,
    setEditClinicHoursModal,
    editHolidaysModal,
    setEditHolidaysModal,
    appointmentBookingModal,
    setAppointmentBookingModal,
    contactUsModal,
    setContactUsModal,
    paymongoModal,
    setPaymongoModal,
    cartModal,
    paymentModal,
    userRolesModal,
    setUserRolesModal,
    calendarOverviewModal,
    setCalendarOverviewModal,
  } = useSignInContext();

  useEffect(() => {
    if (calendarOverviewModal) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
  }, [calendarOverviewModal]);

  return (
    <div>
      <Head>
        <title>Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence
      // initial={true}
      // exitBeforeEnter={true}
      // onExitComplete={() => null}
      >
        {signInModal && <SignInModal />}
        {signUpModal && <SignUpModal />}
        {userDetailsModal && <UserDetailsModal />}
        {specialistDetailsModal && <SpecialistDetailsModal />}
        {amendClinicHoursModal && <AmendClinicHoursModal />}
        {editClinicHoursModal && <EditClinicHoursModal />}
        {editHolidaysModal && <HolidaysModal />}
        {appointmentBookingModal && <AppointmentBookingModal />}
        {contactUsModal && <ContactUsModal />}
        {paymongoModal && <PaymongoHome />}
        {cartModal && <Cart />}
        {paymentModal && <Payment />}
        {userRolesModal && <UserRolesModal />}

        {calendarOverviewModal && <CalendarOverview />}
      </AnimatePresence>
      <div className="">
        <Header />
        <main className={`${calendarOverviewModal ? "" : ""} `}>
          {/* <Calendar /> */}
          <OurDoctors />
        </main>
      </div>
    </div>
  );
}
