import format from "date-fns/format";
import Head from "next/head";
import Image from "next/image";
import AmendClinicHoursModal from "../components/AmendClinicHoursModal";
import EditClinicHoursModal from "../components/EditClinicHoursModal";
import Calendar from "../components/Calendar";
import Header from "../components/Header";
import SignInModal from "../components/SignInModal";
import SignUpModal from "../components/SignUpModal";
import UserDetailsModal from "../components/UserDetailsModal";

import { useSelectedDateContext } from "../contextProvider/SelectedDateContext";
import { useSignInContext } from "../contextProvider/SignInContext";
import HolidaysModal from "../components/HolidaysModal";
import OurDoctors from "../components/OurDoctors";
import SpecialistDetailsModal from "../components/SpecialistDetailsModal";
import AppointmentBookingModal from "../components/AppointmentBookingModal";
import { ContactUs } from "../components/EmailForm";
import ContactUsModal from "../components/ContactUsModal";

export default function Home() {
  const { selectedDate } = useSelectedDateContext();
  const {
    signInModal,
    setSignInModal,
    signUpModal,
    setSignUpModal,
    forgotPasswordModal,
    setForgotPasswordModal,
    currentUserID,
    setCurrentUserID,
    userDetailsModal,
    setUserDetailsModal,
    specialistDetailsModal,
    setSpecialistDetailsModal,
    amendClinicHoursModal,
    setAmendClinicHoursModal,
    editClinicHoursModal,
    setEditClinicHoursModal,
    editHolidaysModal,
    setEditHolidaysModal,
    appointmentBookingModal,
    setAppointmentBookingModal,
    contactUsModal,
    setContactUsModal,
  } = useSignInContext();

  return (
    <div>
      <Head>
        <title>Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {signInModal && <SignInModal />}
      {signUpModal && <SignUpModal />}
      {userDetailsModal && <UserDetailsModal />}
      {specialistDetailsModal && <SpecialistDetailsModal />}
      {amendClinicHoursModal && <AmendClinicHoursModal />}
      {editClinicHoursModal && <EditClinicHoursModal />}
      {editHolidaysModal && <HolidaysModal />}
      {appointmentBookingModal && <AppointmentBookingModal />}
      {contactUsModal && <ContactUsModal />}
      <Header />
      <main>
        {/* <Calendar /> */}
        <OurDoctors />
      </main>
    </div>
  );
}
